<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
    <mrow>
        <mi>&#x3C3;</mi>
        <mo>=</mo>
        <msqrt>
            <mrow>
                <mfrac>
                    <mrow>
                        <mn>1</mn>
                    </mrow>
                    <mrow>
                        <mi>N</mi>
                    </mrow>
                </mfrac>
            <mrow>
                <munderover>
                    <mrow>
                        <mo>&#x2211;</mo>
                    </mrow>
                    <mrow>
                        <mi>i</mi>
                        <mo>=</mo>
                        <mn>1</mn>
                    </mrow>
                    <mrow>
                        <mi>N</mi>
                    </mrow>
                </munderover>
                <mrow>
                    <msup>
                        <mrow>
                            <mo>(</mo>
                            <msub>
                                <mrow>
                                    <mi>x</mi>
                                </mrow>
                                <mrow>
                                    <mi>i</mi>
                                </mrow>
                            </msub>
                            <mo>&#x2212;</mo>
                            <mi>&#x3BC;</mi>
                            <mo>)</mo>
                        </mrow>
                        <mrow>
                            <mn>2</mn>
                        </mrow>
                    </msup>
                </mrow>
            </mrow>
            </mrow>
        </msqrt>
        <mo>.</mo>
    </mrow>
</math>